CREATE USER mo_paia_service WITH password 'mo_paia_service';

CREATE SCHEMA mopaia;

GRANT USAGE ON SCHEMA public TO mo_paia_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, UPDATE, INSERT, DELETE, TRUNCATE ON TABLES TO mo_paia_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO mo_paia_service;

GRANT USAGE ON SCHEMA mopaia TO mo_paia_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA mopaia GRANT SELECT, UPDATE, INSERT, DELETE, TRUNCATE ON TABLES TO mo_paia_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA mopaia GRANT USAGE ON SEQUENCES TO mo_paia_service;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;
GRANT EXECUTE ON FUNCTION uuid_generate_v4() to mo_paia_service;
