server:
  port: 8080
  compression:
    enabled: true
  servlet:
    context-path: /

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /

spring:
  application:
    name: mo-paia-service
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
      schema: mopaia
      username: mo_paia_service
      password: mo_paia_service
      driver-class-name: org.postgresql.Driver
      maximum-pool-size: 10
      connection-timeout: 10000
